apiVersion: v1                      # Use core API version v1 – this is where Secret, ConfigMap, Service etc. are defined
kind: Secret                        # This manifest defines a Kubernetes Secret (for sensitive data like passwords, tokens)

metadata:
  name: secret                      # Name of the Secret – Deployments will refer to it via secretKeyRef.name

type: Opaque                        # Secret type: "Opaque" = generic key/value pairs encoded in base64

data:                               # Data section – EVERY value here must be base64-encoded (not plain text)
  mysql-username: YWRtaW4=          # base64("admin") – MySQL username used in SPRING_DATASOURCE_USERNAME
  mysql-password: UXdlcnR5MTIzJA==  # base64("Qwerty123$") – MySQL password used in SPRING_DATASOURCE_PASSWORD
                                    # These keys are referenced in Deployments like:
                                    #   secretKeyRef:
                                    #     name: secret          -> this Secret (metadata.name)
                                    #     key: mysql-username   -> which key from data to inject into the env var
